name: Inspection

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: ['ubuntu-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codespell flake8 -r requirements.txt
    - name: Test
      run: |
        echo index.%EXT% > tmp_wordlist.txt
        echo testphp.vulnweb.com > tmp_targets.txt
        python3 dirsearch.py -u https://example.com -o tmp_report.json --format json --force-recursive -R 3 --full-url -w tmp_wordlist.txt
        python3 dirsearch.py -l tmp_targets.txt --subdirs /,admin/ -X conf -q -L -f -i 200 --user-agent a --log tmp_log.txt -w tmp_wordlist.txt
        python3 dirsearch.py -u https://localhost --ip 93.184.216.34 --max-rate 2 -H K:V --random-agent --log tmp.log --only-selected -w tmp_wordlist.txt
        echo https://self-signed.badssl.com | python3 dirsearch.py --stdin --max-time 9 --auth u:p --auth-type basic --scheme http -w tmp_wordlist.txt

    - name: Lint
      run: |
        flake8 . --exclude=thirdparty --count --ignore=E501,E701,F403,F405,F524,W503 --show-source --statistics
        # exit-zero treats all errors as warnings.  Max complexity is currently 77.
        flake8 . --exclude=thirdparty --count --ignore=E501 --exit-zero --max-complexity=10 --show-source --statistics
    - name: Codespell
      run: codespell --ignore-words-list="cros,hist" --skip="./db/dicc.txt,./dirsearch/db/dicc.txt,./thirdparty"
